name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: iluwaaa
          template: classic
          base: ""
          config_timezone: Asia/Novosibirsk
          plugin_code: yes
          plugin_code_languages: c#, pgsql, sql
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: all
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_played_at: yes
          plugin_music_playlist: https://open.spotify.com/playlist/37i9dQZEVXbMDoHDwVN2tF
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: 31nas3lfwrpcwsibtix7guo6rjou
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
